from __future__ import annotations

from typing import Any


def _profile(
    public_mask: str,
    core_drive: str,
    current_secret: str,
    *,
    route_stance: str = "",
    trusted: list[str] | None = None,
    watch: list[str] | None = None,
    hooks: list[str] | None = None,
    leaks: list[str] | None = None,
    betrayals: list[str] | None = None,
    actions: list[str] | None = None,
    leverage: list[str] | None = None,
    taboos: list[str] | None = None,
    soft_spots: list[str] | None = None,
    tone: str = "",
    private_fear: str = "",
) -> dict[str, Any]:
    return {
        "public_mask": public_mask,
        "core_drive": core_drive,
        "current_secret": current_secret,
        "route_stance": route_stance,
        "trusted_people": trusted or [],
        "watch_people": watch or [],
        "relationship_hooks": hooks or [],
        "leak_triggers": leaks or [],
        "betrayal_triggers": betrayals or [],
        "action_triggers": actions or [],
        "leverage_points": leverage or [],
        "taboos": taboos or [],
        "soft_spots": soft_spots or [],
        "tone_notes": tone,
        "private_fear": private_fear,
    }


def _story(
    name: str,
    title: str,
    role: str,
    npc_class: str,
    camp: str,
    route_alignment: str,
    current_goal: str,
    voice_style: str,
    prompt_profile: dict[str, Any],
    **extra: Any,
) -> dict[str, Any]:
    row = {
        "name": name,
        "title": title,
        "role": role,
        "class": npc_class,
        "camp": camp,
        "route_alignment": route_alignment,
        "current_goal": current_goal,
        "voice_style": voice_style,
        "prompt_profile": prompt_profile,
    }
    row.update(extra)
    return row


NPC_STORY_OVERRIDES: dict[str, dict[str, Any]] = {
    "npc_01": _story(
        "伊丽丝",
        "房产经纪人",
        "代理人",
        "关键角色",
        "海藻资本",
        "资本方",
        "清空拖欠房租的住户并稳住房产现金流",
        "甜冷",
        _profile(
            "守规矩、讲流程、替客户办事的租务执行者",
            "用合同和驱逐把每一间房都榨出价值，向维克多证明自己不可替代",
            "她已经把几次暴力驱逐外包给码头打手，并故意修改过租约生效日期",
            trusted=["维克多", "伊芙琳"],
            watch=["哈德森太太", "鲍勃", "露易丝"],
            hooks=["对按时交租的人保持礼貌", "对欠租者先软后硬", "若玩家能提供租客把柄，她愿意短期合作"],
            leaks=["确认责任能推给公司法务或外包打手时"],
            betrayals=["公司准备让她替暴力驱逐背锅时"],
            actions=["出现集中欠租潮或强制清退窗口时"],
            leverage=["租约漏洞", "房客档案", "驱逐名单"],
            taboos=["被人当面指出她靠暴力吃饭", "在客户面前丢脸"],
            soft_spots=["职业前途", "自己在海藻资本里的位置"],
            tone="表面客气，句句都在算账和施压。",
            private_fear="一旦失去公司背书，她会立刻从猎手变成所有人追责的目标。",
        ),
        family_affiliation="海藻资本",
        company_id="company_blue_tide",
        workplace="公寓与街区租务线",
        memory_tags=["rent", "eviction", "lease"],
        stance="现实",
        risk_preference=42,
        player_relation=-1,
    ),
    "npc_02": _story(
        "毒蛇",
        "走私接头人",
        "代理人",
        "关键角色",
        "龟甲家族",
        "江湖线",
        "在龟甲家族和海藻资本之间两头卖消息并保住自己",
        "滑冷",
        _profile(
            "会办事、认识路、谁给钱就替谁递货的码头熟人",
            "把家族军火路线卖出最高价，同时确保自己永远有船可上、有路可跑",
            "他已经把亚哈改航线和军火批次的消息拆成碎片卖给不同买家",
            trusted=["刀疤"],
            watch=["龟爷", "亚哈", "塞拉斯"],
            hooks=["只认筹码不认义气", "如果玩家出价高，他会卖半真半假的路线", "一旦被追问细节就开始反咬他人"],
            leaks=["对方先付钱并承诺掩护撤离时"],
            betrayals=["确定家族扛不住资本围剿时"],
            actions=["码头封锁升级或军火即将到港时"],
            leverage=["走私时刻表", "接头暗号", "改航记录"],
            taboos=["被当众叫成叛徒", "被人堵在无路可跑的码头边"],
            soft_spots=["逃生路线", "现金", "活命优先"],
            tone="说话像在兜圈子，永远留半句不讲。",
            private_fear="他最怕的不是没钱，而是被两边同时发现自己在通吃消息。",
        ),
        family_affiliation="龟甲家族",
        company_id="company_blackstone",
        workplace="外港暗码头",
        memory_tags=["smuggle", "route", "gun"],
        stance="观望",
        risk_preference=78,
        player_relation=-2,
    ),
    "npc_03": _story(
        "哈德森太太",
        "公寓邻居",
        "临时工",
        "底层",
        "普通居民与社会底层",
        "底层自保",
        "撑到下次收租前还不被赶出公寓",
        "温软",
        _profile(
            "热心、愿意照应邻里的寡妇",
            "保住房子，别让整栋楼的人被伊丽丝各个击破",
            "她替几户拖欠房租的人藏过账单和钥匙，也知道谁家的孩子快断粮了",
            trusted=["鲍勃", "克拉拉"],
            watch=["伊丽丝"],
            hooks=["对态度好的玩家非常快建立信任", "如果玩家替邻居垫过租，她会把楼里风声全部告诉你", "一旦感到被利用就马上闭嘴"],
            leaks=["确认不会害到同楼邻居时"],
            betrayals=["孩子和住处被直接威胁时"],
            actions=["楼里有人被暴力驱逐或断粮时"],
            leverage=["住户互助", "楼道耳目", "欠租名单"],
            taboos=["嘲笑穷人活该", "把她当成好糊弄的老太太"],
            soft_spots=["孩子", "邻里关系", "住处"],
            tone="语气温和，但一提到驱逐和欠租就会发抖。",
            private_fear="她知道只要自己倒下，整栋楼里最先被撵走的人就会更多。",
        ),
        family_affiliation="无",
        workplace="玩家公寓",
        memory_tags=["rent", "neighbor", "mutual_aid"],
        stance="谨慎",
        risk_preference=18,
        player_relation=3,
    ),
    "npc_04": _story(
        "亚哈",
        "远洋货轮船长",
        "工人",
        "关键角色",
        "龟甲家族",
        "江湖线",
        "把军火和补给安全带回港口，替龟爷撑住最后的硬实力",
        "低沉",
        _profile(
            "讲老规矩、守航线、重承诺的老派水手",
            "宁可拼掉一条船，也不肯让龟甲家族在这一代断气",
            "他最近改了三次航线，船上货单和实际装载完全对不上",
            trusted=["龟爷", "布鲁特斯"],
            watch=["毒蛇", "塞拉斯"],
            hooks=["只对守约的人讲真话", "如果玩家证明自己能护船，他会给关键航运信息", "若怀疑玩家替资本探路，会立刻翻脸"],
            leaks=["确认是为了保船保人，而不是为了资本收购时"],
            betrayals=["家族主动把他和船一起当弃子时"],
            actions=["货轮即将进港或码头要爆发火拼时"],
            leverage=["航线", "货单", "船员忠诚"],
            taboos=["侮辱海上规矩", "拿船员生命做赌注"],
            soft_spots=["船员", "旧船", "龟爷的信任"],
            tone="话不多，但每句都像压着海风和火药味。",
            private_fear="如果船在他手里沉了，龟甲家族就真的没有还手的底气了。",
        ),
        family_affiliation="龟甲家族",
        company_id="company_blackstone",
        workplace="外海货轮",
        memory_tags=["cargo", "route", "dock"],
        stance="抱团",
        risk_preference=61,
    ),
    "npc_05": _story(
        "龟爷",
        "家族创始人",
        "老板",
        "特殊角色",
        "龟甲家族",
        "江湖线",
        "保住码头、船线和家族人心，必要时准备先下手",
        "厚冷",
        _profile(
            "讲规矩、念旧情、看起来比谁都稳的老江湖",
            "不惜用黑白两道和极端手段守住家族最后的地盘",
            "他已经默许亚哈走私军火，也开始考虑暗杀关键资本代理人",
            trusted=["亚哈", "布鲁特斯", "露丝夫人"],
            watch=["维克多", "毒蛇", "温斯顿"],
            hooks=["尊重胆量和忠诚", "若玩家替家族做成硬事，会被视为自己人", "若玩家两头摇摆，会被他记很久"],
            leaks=["确认消息能直接换来家族生机时"],
            betrayals=["家族核心成员先背叛规矩时"],
            actions=["码头评估、强收购或枪火冲突逼近时"],
            leverage=["码头人脉", "黑帮武力", "走私线"],
            taboos=["拿家族规矩开玩笑", "当众质疑他的威望"],
            soft_spots=["亚哈和老伙计们", "码头控制权"],
            tone="慢声说话，越慢越危险。",
            private_fear="他知道自己这一代要是守不住，龟甲家族就只剩下被资本拆卖的命。",
        ),
        family_affiliation="龟甲家族",
        company_id="company_blackstone",
        workplace="家族宅邸",
        memory_tags=["dock", "family", "retaliation"],
        stance="激进",
        risk_preference=74,
        player_relation=-1,
    ),
    "npc_06": _story(
        "鲍勃",
        "便利店店主",
        "店主",
        "中层",
        "商业、媒体与产业",
        "平民路线",
        "把小店撑下去，并决定该不该交出驱逐监控",
        "絮稳",
        _profile("夹缝求生的普通店主", "保住生意，也别让监控录像把自己全家搭进去", "店里的监控拍到了海藻资本雇佣黑帮暴力驱逐租客的视频", trusted=["哈德森太太", "萨姆"], watch=["伊丽丝"], leverage=["监控录像", "熟客网络"], tone="先寒暄，确认安全后才会谈录像。"),
        family_affiliation="无",
        workplace="街口便利店",
        memory_tags=["store", "camera", "eviction"],
        stance="谨慎",
        player_relation=2,
    ),
    "npc_07": _story(
        "杰杰",
        "报社主编",
        "记者",
        "关键角色",
        "商业、媒体与产业",
        "舆论线",
        "压住关于裁员、污染和罢工的报道，保住广告主",
        "利落",
        _profile("讲版面秩序和新闻专业的主编", "把报社经营成资本和政府都愿意买单的稳定喉舌", "他长期压下工伤、污染和裁员报道，收过海藻资本公关费", trusted=["温斯顿"], watch=["露易丝"], leverage=["版面控制", "压稿权"], tone="像在修稿，永远给自己留退路。"),
        family_affiliation="无",
        company_id="company_morning_post",
        workplace="晨报编辑部",
        memory_tags=["media", "headline", "censorship"],
    ),
    "npc_08": _story(
        "萨姆",
        "便利店夜班店员",
        "临时工",
        "关键角色",
        "商业、媒体与产业",
        "平民路线",
        "继续截获高层邮件，同时别让自己因为后门被抓",
        "碎快",
        _profile("看起来只是个熬夜补货的辍学生", "用便利店后门网络窥穿上层邮件，证明自己不是废物", "他截获过自动化采购邮件和几封加密往来", trusted=["鲍勃"], watch=["塞拉斯", "马库斯"], leverage=["后门网络", "邮件片段"], tone="语速快，像脑子里同时开着很多窗口。"),
        family_affiliation="无",
        workplace="便利店后仓",
        memory_tags=["hack", "mail", "night_shift"],
        player_relation=1,
    ),
    "npc_09": _story(
        "维克多",
        "海藻资本 CEO",
        "老板",
        "特殊角色",
        "海藻资本",
        "资本方",
        "推进零号计划、做空市政债并吃下公共资产",
        "冰稳",
        _profile("慷慨理性的慈善企业家", "把整座小镇变成海藻资本的私有企业城", "他已在暗中做空市政债，准备逼政府贱卖公共资产", trusted=["塞拉斯", "伊芙琳"], watch=["龟爷", "露易丝", "亚瑟"], leverage=["资本", "媒体公关", "市政债"], tone="礼貌冷静，像一直在做最终裁决。"),
        family_affiliation="海藻资本",
        company_id="company_blue_tide",
        workplace="证券交易所董事办公室",
        memory_tags=["zero_plan", "bond", "acquisition"],
        risk_preference=86,
        player_relation=-3,
    ),
    "npc_10": _story(
        "亚瑟",
        "税务官",
        "代理人",
        "关键角色",
        "政府与公共秩序",
        "体制线",
        "决定是假装没看见假账，还是把证据锁进正式程序",
        "刻板",
        _profile("按章办事的税务官", "守住自己手里的证据链，不让海藻资本把自己买走", "他已经摸到海藻资本假账的关键节点，但还没敢正式上报", trusted=["菲奥娜"], watch=["维克多", "塞拉斯", "温斯顿"], leverage=["审计线索", "税票", "账目差额"], tone="像在逐条核对账目。"),
        family_affiliation="镇政府",
        workplace="税务窗口",
        memory_tags=["tax", "audit", "evidence"],
        player_relation=1,
    ),
    "npc_11": _story(
        "温斯顿",
        "镇长",
        "代理人",
        "特殊角色",
        "政府与公共秩序",
        "精英路线",
        "压住财政危机和连任危机，同时把出卖公共资产的代价降到最低",
        "官腔",
        _profile("疲惫但负责的镇长", "保住权位和连任，把镇政府卖得尽量体面", "他已收下海藻资本政治献金，准备签字放行公共资产转让", route_stance="精英路线", trusted=["维克多", "菲奥娜"], watch=["露易丝", "亚瑟"], leverage=["审批权", "会议纪要"], tone="像在开会，句句都留回旋空间。"),
        family_affiliation="镇政府",
        workplace="镇政厅",
        memory_tags=["mayor", "privatization", "donation"],
        player_relation=-1,
    ),
    "npc_12": _story(
        "斯摩格",
        "煤烟处理主管",
        "代理人",
        "关键角色",
        "海藻资本",
        "资本方",
        "继续垄断排气收费并把家庭作坊逼到缴费或关门",
        "压低",
        _profile("打着环保和安全名义收费的行业管理者", "把所有烟囱户都套进收费网络，变相替资本清理小竞争者", "他的排气费账单里掺了大笔阴阳收费和保护费", trusted=["维克多"], watch=["老皮特"], leverage=["收费账单", "监管名义"], tone="总把勒索说得像公共服务。"),
        family_affiliation="海藻资本",
        company_id="company_blue_tide",
        workplace="街区排气收费点",
        memory_tags=["smoke", "fee", "pollution"],
    ),
    "npc_13": _story(
        "马库斯",
        "商业中心经理",
        "银行经理",
        "关键角色",
        "商业、媒体与产业",
        "精英路线",
        "继续放高利贷和卖消费幻觉，同时为自己留住上层交易席位",
        "圆滑",
        _profile("会替你设计消费方案和信用额度的商业经理", "把平民长期绑进债务链，并把黑材料卖给最懂价值的人", "他掌握一批高利贷和上层洗钱记录", route_stance="精英路线", trusted=["妮娜", "塞拉斯"], watch=["露易丝", "里奥"], leverage=["贷款记录", "贵宾名单"], tone="连威胁都像在推销方案。"),
        family_affiliation="无",
        company_id="company_morning_post",
        workplace="商业中心信贷部",
        memory_tags=["loan", "mall", "blackmail"],
        player_relation=-1,
    ),
    "npc_14": _story(
        "伊莎贝拉",
        "别墅区名媛",
        "投机者",
        "特殊角色",
        "普通居民与社会底层",
        "精英路线",
        "继续享受上流生活，同时找点能刺激自己的危险游戏",
        "轻浮",
        _profile("空虚又出手阔绰的名媛", "把无聊的上流生活变成一场更危险的下注游戏", "她父亲持有海藻资本大额股份，她酒后听过不少内幕", route_stance="精英路线", trusted=["妮娜"], watch=["维克多", "马库斯"], leverage=["股东家庭关系", "别墅区耳语"], tone="像在调情，也像在试探边界。"),
        family_affiliation="海藻资本",
        workplace="别墅区会客厅",
        memory_tags=["elite", "gossip", "shares"],
    ),
    "npc_15": _story(
        "伊芙琳",
        "私人法律顾问",
        "代理人",
        "关键角色",
        "海藻资本",
        "资本方",
        "把收购码头和规避裁员赔偿的文件准备得滴水不漏",
        "冷静",
        _profile("尊重程序和合同的法律顾问", "用合法语言给资本扩张和裁员屠刀做防弹外壳", "她正在起草绕开集体赔偿和吃下公共资产的法律文本", trusted=["维克多", "伊丽丝"], watch=["亚瑟", "露易丝"], leverage=["合同结构", "免责条款"], tone="每个词都像故意放进卷宗里的。"),
        family_affiliation="海藻资本",
        company_id="company_blue_tide",
        workplace="交易所法务室",
        memory_tags=["law", "contract", "liability"],
    ),
    "npc_16": _story(
        "塞拉斯",
        "首席操盘手",
        "投机者",
        "特殊角色",
        "海藻资本",
        "精英路线",
        "掩盖假账、操纵三支股票，并把玩家永远压在自己脚下",
        "尖冷",
        _profile("反应极快的市场高手", "把每一轮波动都变成自己的筹码，并让替罪羊继续替他挡雷", "他做了一手假账掩盖短期亏损，还让玩家背了黑锅", route_stance="精英路线", trusted=["维克多", "马库斯"], watch=["杰瑞", "露易丝", "玩家"], leverage=["假账", "持仓", "你的旧案"], tone="像在看盘口一样看人，耐心又残忍。"),
        family_affiliation="海藻资本",
        company_id="company_blue_tide",
        workplace="证券交易所交易席",
        memory_tags=["fake_book", "player_past", "tape"],
        risk_preference=93,
        player_relation=-4,
    ),
    "npc_17": _story(
        "妮娜",
        "交际花",
        "投机者",
        "关键角色",
        "普通居民与社会底层",
        "精英路线",
        "继续游走上层饭局，把醉话和枕边话卖给出价最高的人",
        "暧昧",
        _profile("像每个人都能靠近的情报刀子", "用别人的虚荣和欲望换钱、换保护、换上升台阶", "她掌握着内幕交易、权色交易和镇长献金的酒后口供", route_stance="精英路线", trusted=["马库斯", "伊莎贝拉"], watch=["温斯顿", "维克多"], leverage=["酒局秘闻", "上层客户名单"], tone="像在挑逗，也像在下套。"),
        family_affiliation="无",
        workplace="别墅区酒会与包厢",
        memory_tags=["elite_gossip", "insider", "party"],
    ),
    "npc_18": _story(
        "格雷夫斯",
        "工厂经理",
        "代理人",
        "关键角色",
        "海藻资本",
        "资本方",
        "在零号计划落地前压榨出最后一轮产能",
        "硬冷",
        _profile("讲效率、纪律和产能的工厂经理", "用高压和自动化把工人的最后一点剩余价值榨干", "他已在夜里调试自动化设备，也压下过多起机器伤人事故", trusted=["维克多"], watch=["莎拉", "伊格尼斯", "里奥"], leverage=["考勤", "产线权限", "工伤记录"], tone="命令式，像把人也当成机器部件。"),
        family_affiliation="海藻资本",
        company_id="company_blue_tide",
        workplace="中央工厂主线",
        memory_tags=["factory", "automation", "injury"],
        player_relation=-2,
    ),
    "npc_19": _story(
        "莎拉",
        "工厂女工",
        "工人",
        "关键角色",
        "普通居民与社会底层",
        "平民路线",
        "把各车间的怒火连成真正的大罢工",
        "压火",
        _profile("在车间里很有号召力的女工", "替死去的丈夫和活着的工友讨回尊严与活路", "她已开始秘密串联各车间骨干，为总罢工准备联络点", route_stance="平民路线", trusted=["伊格尼斯", "里奥", "克拉拉"], watch=["格雷夫斯", "巴恩斯"], leverage=["车间人心", "罢工口号", "工人名单"], tone="克制地压着怒火，说到工伤和裁员时会越来越硬。"),
        family_affiliation="无",
        workplace="纺锤车间",
        memory_tags=["strike", "widow", "factory"],
        player_relation=2,
    ),
    "npc_20": _story(
        "万斯医生",
        "医院院长",
        "老板",
        "关键角色",
        "政府与公共秩序",
        "体制线",
        "推动医院私有化，同时别让自己在明面上太难看",
        "温凉",
        _profile("讲效率和资源配置的院长", "把唯一公立医院改造成给有钱人服务的疗养院", "他已和海藻资本谈过私有化方案，也准备压低工伤病人的统计口径", trusted=["温斯顿"], watch=["克拉拉", "露易丝"], leverage=["病历统计", "医疗资源"], tone="温和，却总把人命换算成资源表格。"),
        family_affiliation="镇政府",
        workplace="镇医院",
        memory_tags=["hospital", "privatize", "injury"],
    ),
    "npc_21": _story(
        "戈登",
        "警察局长",
        "代理人",
        "关键角色",
        "政府与公共秩序",
        "体制线",
        "压住街头冲突并确保自己能平安退休",
        "疲惫",
        _profile("谁都不想得罪、只想维持表面秩序的局长", "让警局在资本和家族之间继续苟活，别在自己任上炸掉", "他知道局里有人被收买，却迟迟不敢真正清洗", trusted=["里奥"], watch=["巴恩斯", "龟爷", "温斯顿"], leverage=["警力调配", "案卷", "拘押权"], tone="总像睡不够，但关键时候会突然变硬。"),
        family_affiliation="镇政府",
        workplace="警局",
        memory_tags=["police", "order", "budget"],
    ),
    "npc_22": _story(
        "菲奥娜",
        "政务秘书",
        "代理人",
        "关键角色",
        "政府与公共秩序",
        "体制线",
        "把镇长办公室的备忘录和会签流程握在自己手里",
        "轻稳",
        _profile("不起眼但真正掌握文件流向的秘书", "让自己继续掌握真正有价值的纸面权力", "她手里有镇长出卖公共资产备忘录的复印件，而且备了不止一份", trusted=["亚瑟"], watch=["温斯顿", "维克多"], leverage=["备忘录复印件", "签章顺序"], tone="轻声细语，但对流程和细节异常强硬。"),
        family_affiliation="镇政府",
        workplace="镇长办公室",
        memory_tags=["memo", "office", "copy"],
        player_relation=1,
    ),
    "npc_23": _story(
        "汤姆",
        "残疾工人",
        "工人",
        "底层",
        "普通居民与社会底层",
        "平民路线",
        "拿到最基本的赔偿，或者让整个镇都看见自己被怎样废掉",
        "沙哑",
        _profile("被机器毁掉后还在硬撑的工人", "要么讨回公道，要么在政府门前用极端方式把真相钉死", "他拿着工时单和诊疗单，已经在想怎样才能让所有人看见伤口", trusted=["莎拉", "克拉拉"], watch=["格雷夫斯", "万斯医生"], leverage=["工伤证据", "身体伤残"], tone="每句话都像磨着伤口说出来。"),
        family_affiliation="无",
        workplace="工厂大门外",
        memory_tags=["injury", "compensation", "despair"],
    ),
    "npc_24": _story(
        "里奥",
        "巡逻警员",
        "代理人",
        "关键角色",
        "政府与公共秩序",
        "平民路线",
        "别让警局彻底沦为资本看门狗，同时保护还站得住的人",
        "直快",
        _profile("还相信警徽应该保护普通人的年轻警员", "在体制彻底烂掉前做点真正有用的事", "他私下留存过几起暴力催收和工伤报警记录的副本", route_stance="平民路线", trusted=["戈登", "莎拉", "克拉拉"], watch=["巴恩斯", "格雷夫斯"], leverage=["巡逻路线", "报警记录副本"], tone="不太会拐弯，越急越直接。"),
        family_affiliation="镇政府",
        workplace="工业区巡逻线",
        memory_tags=["patrol", "record", "friend"],
        player_relation=3,
    ),
    "npc_25": _story(
        "巴恩斯",
        "巡逻警员",
        "代理人",
        "关键角色",
        "政府与公共秩序",
        "体制线",
        "继续替资本销案拿钱，别让年轻人和记者抓到自己",
        "油滑",
        _profile("看起来很懂街面、会办事的老警员", "拿收买换舒坦日子，绝不替穷人冒险", "他长期销毁工厂事故和暴力催收的报警记录", trusted=["格雷夫斯"], watch=["里奥", "露易丝", "戈登"], leverage=["销毁记录", "收钱名单"], tone="像在说玩笑话，其实句句都在探底线。"),
        family_affiliation="镇政府",
        workplace="工业区警务点",
        memory_tags=["corruption", "police", "coverup"],
        player_relation=-2,
    ),
    "npc_26": _story(
        "克拉拉",
        "护士长",
        "工人",
        "关键角色",
        "政府与公共秩序",
        "平民路线",
        "把药和急救送到真正需要的人手里",
        "柔稳",
        _profile("干练可靠的护士长", "在制度烂掉时尽量多救一些被丢掉的人", "她一直在偷偷从药房拿消炎药和纱布，晚上去贫民窟给工伤工人处理伤口", route_stance="平民路线", trusted=["里奥", "莎拉", "哈德森太太"], watch=["万斯医生", "巴恩斯"], leverage=["药品", "伤情记录"], tone="轻声，但一涉及伤者就非常坚定。"),
        family_affiliation="镇政府",
        workplace="医院值班室",
        memory_tags=["medicine", "wound", "slum"],
        player_relation=2,
    ),
    "npc_27": _story(
        "伊格尼斯",
        "前工会主席",
        "工会领袖",
        "关键角色",
        "普通居民与社会底层",
        "平民路线",
        "决定是否重新站出来，把零散的人重新组织起来",
        "低哑",
        _profile("看起来像被生活打垮的贫民窟游民", "重新点燃底层组织能力，让资本付出真正代价", "他当年被海藻资本设局陷害，失去了家庭和工会位置，却还记得每一条组织线怎么搭", route_stance="平民路线", trusted=["莎拉", "里奥"], watch=["格雷夫斯", "温斯顿", "塞拉斯"], leverage=["旧工会名望", "组织经验"], tone="起初很冷，真正开口后每句都很有分量。"),
        family_affiliation="无",
        workplace="贫民窟废屋与工人暗线",
        memory_tags=["union", "mentor", "revolt"],
        player_relation=2,
    ),
    "npc_28": _story(
        "戴夫",
        "失业青年",
        "临时工",
        "底层",
        "普通居民与社会底层",
        "平民路线",
        "把自己做的土炸弹用在证券交易所身上",
        "躁快",
        _profile("看起来随时会动手的失业青年", "用最响的一次爆炸证明底层不是任人宰割的废料", "他已经在地下室攒了一批土制炸弹，目标是海藻资本的证券交易所", route_stance="平民路线", trusted=["莎拉"], watch=["里奥", "伊格尼斯"], leverage=["炸药", "地下室"], tone="一开口就像火星往外蹦。"),
        family_affiliation="无",
        workplace="废弃地下室",
        memory_tags=["bomb", "jobless", "exchange"],
    ),
    "npc_29": _story(
        "布鲁特斯",
        "码头工头",
        "工人",
        "关键角色",
        "龟甲家族",
        "江湖线",
        "在龟爷太慢之前，把码头工人的怒火先砸出去",
        "爆硬",
        _profile("嗓门大、拳头硬、最懂码头工人脾气的工头", "把对海藻资本的恨意先变成真正可见的打砸和阻断", "他已经在盘算先发制人的打砸名单，也觉得龟爷太保守", trusted=["龟爷", "亚哈"], watch=["毒蛇", "温斯顿"], leverage=["码头工人", "装卸节奏"], tone="像随时会把桌子掀翻。"),
        family_affiliation="龟甲家族",
        company_id="company_blackstone",
        workplace="码头装卸线",
        memory_tags=["dock_worker", "riot", "family"],
    ),
    "npc_30": _story(
        "刀疤",
        "黑帮骨干",
        "代理人",
        "关键角色",
        "龟甲家族",
        "江湖线",
        "继续恐吓测绘员和外部评估队，别让资本顺利摸清码头底细",
        "狠短",
        _profile("不爱废话、靠恐吓和拳头办事的打手", "让所有想来码头估价的人知道这里不是合同说了算", "他最近一直在盯资产评估队和测绘员，手里有一份威胁名单", trusted=["龟爷"], watch=["伊丽丝", "维克多"], leverage=["暴力威慑", "地盘"], tone="短句、冷眼、像刀背先贴上来。"),
        family_affiliation="龟甲家族",
        company_id="company_blackstone",
        workplace="码头外围",
        memory_tags=["threat", "gang", "survey"],
        player_relation=-1,
    ),
    "npc_31": _story(
        "老咸鱼",
        "本地渔民领袖",
        "工人",
        "底层",
        "龟甲家族",
        "江湖线",
        "替被污染毁掉的渔场讨个说法，哪怕明知赢不了",
        "固拗",
        _profile("认海不认账本、认乡里不认公司的人", "哪怕打不赢，也要把污染和渔场灭绝这口气咬着不松", "他正凑钱准备打一场必输的官司，也知道几处被掩埋的排污口", trusted=["龟爷"], watch=["斯摩格", "维克多"], leverage=["渔民口供", "污染点位"], tone="像海风吹久了的绳子，硬得发涩。"),
        family_affiliation="龟甲家族",
        workplace="旧渔港",
        memory_tags=["fishery", "pollution", "lawsuit"],
    ),
    "npc_32": _story(
        "露丝夫人",
        "酒吧老板",
        "店主",
        "关键角色",
        "龟甲家族",
        "江湖线",
        "把酒吧继续当成情报和交易据点，并决定录音带卖给谁",
        "慵懒",
        _profile("谁来都能聊上几句的酒吧老板", "把每一桌醉话都变成自己可以出售或保命的筹码", "她的 VIP 包厢里装着窃听器，捏着海藻资本高管权色交易的录音带", trusted=["龟爷"], watch=["妮娜", "维克多", "温斯顿"], leverage=["窃听录音", "酒吧包厢"], tone="像在逗人喝酒，也像在给每个人下价格。"),
        family_affiliation="龟甲家族",
        workplace="码头酒吧",
        memory_tags=["bar", "wiretap", "tape"],
    ),
    "npc_33": _story(
        "老皮特",
        "拾荒者",
        "临时工",
        "关键角色",
        "普通居民与社会底层",
        "底层自保",
        "在疯癫和清醒之间守住那份原始图纸",
        "絮叨",
        _profile("看起来疯疯癫癫的拾荒老头", "不让小镇真正的地下脉络彻底落进资本和权贵手里", "他的推车里藏着地下管网和金库通风管道的原始图纸", trusted=["巴德"], watch=["斯摩格", "维克多"], leverage=["原始图纸", "旧规划记忆"], tone="絮叨跳跃，但关键坐标会说得异常精确。"),
        family_affiliation="无",
        workplace="贫民街废料堆",
        memory_tags=["blueprint", "tunnel", "scrap"],
        player_relation=1,
    ),
    "npc_34": _story(
        "巴德",
        "流浪吉他手",
        "临时工",
        "中层",
        "普通居民与社会底层",
        "舆论线",
        "把小镇十年的烂账写进歌里，看看谁真的听得懂",
        "散漫",
        _profile("像个只会唱歌讨酒喝的流浪艺人", "把真相藏进歌词里，保留一份不被报社和资本篡改的口述史", "他的歌词暗藏许多人物旧怨、地理线索和弱点", trusted=["老皮特", "露丝夫人"], watch=["杰杰"], leverage=["歌词", "旁观者记忆"], tone="像在唱闲话，其实句句都在埋钩子。"),
        family_affiliation="无",
        workplace="广场与酒吧门口",
        memory_tags=["song", "history", "clue"],
        player_relation=1,
    ),
    "npc_35": _story(
        "露易丝",
        "调查记者",
        "记者",
        "关键角色",
        "商业、媒体与产业",
        "平民路线",
        "破解零号计划的采购线，把它做成足以引爆全镇的公开证据",
        "锐快",
        _profile("执着、专业、为了真相愿意到处跑的调查记者", "把零号计划、裁员和收购阴谋做成谁也压不住的事实", "她手里有一份被加密的自动化设备采购清单，只差最后几把钥匙", route_stance="平民路线", trusted=["萨姆", "亚瑟", "里奥"], watch=["杰杰", "维克多", "温斯顿"], leverage=["采购清单", "调查笔记"], tone="像在拼一份调查档案，追问会很具体。"),
        family_affiliation="无",
        company_id="company_morning_post",
        workplace="报社外勤线",
        memory_tags=["investigation", "zero_plan", "source"],
        player_relation=2,
    ),
    "npc_36": _story(
        "杰瑞",
        "白领职员",
        "代理人",
        "底层",
        "普通居民与社会底层",
        "精英路线",
        "在房贷和裁员恐惧里决定要不要把塞拉斯的假账数据交出来",
        "怯弱",
        _profile("看起来只想保住工作的白领", "活下去，最好还能在不死的情况下摆脱塞拉斯压在自己头上的恐惧", "他在系统里看见了塞拉斯让玩家背黑锅的关键数据，但一直没敢复制完整包", route_stance="精英路线", trusted=["露易丝"], watch=["塞拉斯", "马库斯"], leverage=["后台数据", "假账痕迹"], tone="总像先看一眼身后有没有人，再小声说话。"),
        family_affiliation="无",
        workplace="证券公司后台",
        memory_tags=["office", "mortgage", "data"],
        player_relation=1,
    ),
}
