#target photoshop
app.displayDialogs = DialogModes.NO;
function findDoc(prefix){for(var i=0;i<app.documents.length;i++){if(app.documents[i].name.indexOf(prefix)===0)return app.documents[i];}return null;}
var src=findDoc('ditu_8k_realesrgan.png'); if(!src) throw new Error('source doc not open');
var doc=findDoc('ditu_8k_house_layers_stage1_irregular'); if(doc){app.activeDocument=doc; doc.close(SaveOptions.DONOTSAVECHANGES);}
app.activeDocument=src; doc=src.duplicate('ditu_8k_house_layers_stage1_irregular', false); app.activeDocument=doc; while(doc.layerSets.length>0){doc.layerSets[0].remove();} var base=doc.activeLayer; if(base.isBackgroundLayer){base.isBackgroundLayer=false;} base.name='_source'; var group=doc.layerSets.add(); group.name='ditu_8k_house_layers_stage1_irregular';
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage1_irregular/hilltop_temple_block.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='hilltop_temple_block'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(420, 220);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage1_irregular/hill_stair_shop.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='hill_stair_shop'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(820, 1180);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage1_irregular/closed_market_block.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='closed_market_block'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(560, 1960);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage1_irregular/general_store_block.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='general_store_block'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(900, 2960);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage1_irregular/fish_market_block.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='fish_market_block'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(0, 3440);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage1_irregular/subway_station.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='subway_station'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(120, 4540);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage1_irregular/exchange_row_left.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='exchange_row_left'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(3100, 120);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage1_irregular/exchange_row_mid.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='exchange_row_mid'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(4460, 100);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage1_irregular/stock_exchange.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='stock_exchange'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(5360, 80);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage1_irregular/clocktower_building.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='clocktower_building'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(7440, 20);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage1_irregular/exchange_row_right.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='exchange_row_right'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(6940, 300);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage1_irregular/bank_hall.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='bank_hall'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(2900, 1080);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage1_irregular/bank_side_shop.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='bank_side_shop'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(4580, 1140);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage1_irregular/lower_exchange_stalls.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='lower_exchange_stalls'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(3120, 2000);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage1_irregular/memorial_row.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='memorial_row'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(6600, 760);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage1_irregular/fountain_right_row.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='fountain_right_row'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(6420, 1320);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage1_irregular/warehouse_small.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='warehouse_small'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(5080, 2720);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage1_irregular/iron_claw_factory.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='iron_claw_factory'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(5640, 2460);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage1_irregular/factory_right_row.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='factory_right_row'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(7320, 2100);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage1_irregular/seal_flour.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='seal_flour'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(4940, 3760);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage1_irregular/warehouse_24.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='warehouse_24'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(6340, 4140);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage1_irregular/harbor_office.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='harbor_office'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(7240, 4480);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage1_irregular/lighthouse.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='lighthouse'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(5840, 4340);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage1_irregular/container_yard.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='container_yard'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(6420, 4680);
base.visible=false; var saveFile=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage1_irregular.psd'); var opts=new PhotoshopSaveOptions(); opts.layers=true; opts.embedColorProfile=true; opts.alphaChannels=true; doc.saveAs(saveFile, opts, true, Extension.LOWERCASE);