#target photoshop
app.displayDialogs = DialogModes.NO;
function findDoc(prefix){for(var i=0;i<app.documents.length;i++){if(app.documents[i].name.indexOf(prefix)===0)return app.documents[i];}return null;}
var src=findDoc('ditu_8k_realesrgan.png'); if(!src) throw new Error('source doc not open');
var doc=findDoc('ditu_8k_house_layers_stage2_irregular_no_road'); if(doc){app.activeDocument=doc; doc.close(SaveOptions.DONOTSAVECHANGES);}
app.activeDocument=src; doc=src.duplicate('ditu_8k_house_layers_stage2_irregular_no_road', false); app.activeDocument=doc; while(doc.layerSets.length>0){doc.layerSets[0].remove();} var base=doc.activeLayer; if(base.isBackgroundLayer){base.isBackgroundLayer=false;} base.name='_source'; var group=doc.layerSets.add(); group.name='ditu_8k_house_layers_stage2_irregular_no_road';
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage2_irregular_no_road/hilltop_temple_block.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='hilltop_temple_block'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(500, 220);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage2_irregular_no_road/hill_stair_shop.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='hill_stair_shop'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(860, 1180);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage2_irregular_no_road/closed_market_block.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='closed_market_block'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(620, 1980);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage2_irregular_no_road/general_store_block.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='general_store_block'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(980, 3000);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage2_irregular_no_road/fish_market_block.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='fish_market_block'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(0, 3460);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage2_irregular_no_road/subway_station.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='subway_station'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(160, 4560);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage2_irregular_no_road/exchange_row_left.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='exchange_row_left'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(3140, 120);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage2_irregular_no_road/exchange_row_mid.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='exchange_row_mid'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(4440, 100);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage2_irregular_no_road/stock_exchange.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='stock_exchange'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(5380, 80);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage2_irregular_no_road/clocktower_building.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='clocktower_building'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(7440, 20);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage2_irregular_no_road/exchange_row_right.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='exchange_row_right'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(6940, 300);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage2_irregular_no_road/bank_hall.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='bank_hall'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(2940, 1100);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage2_irregular_no_road/bank_side_shop.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='bank_side_shop'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(4600, 1160);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage2_irregular_no_road/lower_exchange_stalls.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='lower_exchange_stalls'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(3160, 2020);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage2_irregular_no_road/memorial_row.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='memorial_row'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(6620, 780);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage2_irregular_no_road/fountain_right_row.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='fountain_right_row'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(6440, 1340);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage2_irregular_no_road/warehouse_small.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='warehouse_small'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(5100, 2760);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage2_irregular_no_road/iron_claw_factory.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='iron_claw_factory'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(5660, 2480);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage2_irregular_no_road/factory_right_row.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='factory_right_row'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(7340, 2120);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage2_irregular_no_road/seal_flour.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='seal_flour'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(4960, 3780);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage2_irregular_no_road/warehouse_24.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='warehouse_24'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(6360, 4160);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage2_irregular_no_road/harbor_office.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='harbor_office'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(7240, 4480);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage2_irregular_no_road/lighthouse.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='lighthouse'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(5900, 4380);
var f=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage2_irregular_no_road/container_yard.png'); var layerDoc=app.open(f); layerDoc.activeLayer.duplicate(doc, ElementPlacement.PLACEATBEGINNING); layerDoc.close(SaveOptions.DONOTSAVECHANGES); app.activeDocument=doc; var lyr=doc.activeLayer; lyr.name='container_yard'; lyr.move(group, ElementPlacement.INSIDE); lyr.translate(6420, 4720);
base.visible=false; var saveFile=new File('E:/Desktop/gamexu/assets/generated/ditu_8k_house_layers_stage2_irregular_no_road.psd'); var opts=new PhotoshopSaveOptions(); opts.layers=true; opts.embedColorProfile=true; opts.alphaChannels=true; doc.saveAs(saveFile, opts, true, Extension.LOWERCASE);